---
apiVersion: v2
type: application
name: opensearch-stack
description: Cloud Mobility Stack for OpenSearch
home: https://github.com/cloudmobility/charts/tree/master/charts/opensearch-stack
icon: https://portal.cloudmobility.io/icons/charts/opensearch.png
version: 1.0.5
appVersion: "1.0.1"
dependencies:
  - name: opensearch
    version: "1.6.0"
    repository: "https://opensearch-project.github.io/helm-charts/"
  - name: opensearch-dashboards
    version: "1.2.0"
    repository: "https://opensearch-project.github.io/helm-charts/"
  - name: fluentd
    version: "0.3.4"
    repository: "https://fluent.github.io/helm-charts"
maintainers:
  - email: r.mota@kigroup.de
    name: Rubem Mota
annotations:
  enabled: true
